language: python
python:
  - '2.7'
  - '3.2'
  - '3.3'
env:
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
cache:
  directories:
    - "$HOME/.pip-cache/"
install:
  - pip install django==$DJANGO_VERSION
  - pip install --download-cache $HOME/.pip-cache -r requirements-dev.txt
script:
  - py.test tests/
notifications:
  email:
  - csinchok@theonion.com
  on_failure: change
  on_success: change